@startuml

title __AVEMPROJECT's Class Diagram__\n

  namespace avem.basic {
    class avem.basic.AVEMInfo {
    }
  }
  

  namespace avem.basic {
    class avem.basic.AVEMTheme {
    }
  }
  

  namespace avem.basic {
    class avem.basic.AVEMWindows {
    }
  }
  

  namespace avem.controllers {
    class avem.controllers.AVAlert {
    }
  }
  

  namespace avem.controllers {
    class avem.controllers.AccountView {
    }
  }
  

  namespace avem.controllers {
    class avem.controllers.AccountsViewController {
    }
  }
  

  namespace avem.controllers {
    class avem.controllers.CheckInOutEquipment {
    }
  }
  

  namespace avem.controllers {
    class avem.controllers.CheckInOutPageController {
    }
  }
  

  namespace avem.controllers {
    class avem.controllers.DashboardController {
    }
  }
  

  namespace avem.controllers {
    class avem.controllers.EquipmentView {
    }
  }
  

  namespace avem.controllers {
    class avem.controllers.Main {
    }
  }
  

  namespace avem.controllers {
    class avem.controllers.MultiSelectTableView {
    }
  }
  

  namespace avem.controllers {
    class avem.controllers.RefreshPageController {
    }
  }
  

  namespace avem.controllers {
    class avem.controllers.ReserveEquipment {
    }
  }
  

  namespace avem.controllers {
    class avem.controllers.ReserveViewController {
    }
  }
  

  namespace avem.controllers {
    class avem.controllers.SigningController {
    }
  }
  

  namespace avem.controllers {
    class avem.controllers.TableViewController {
    }
  }
  

  namespace avem.core {
    class avem.core.AVAccount {
    }
  }
  

  namespace avem.core {
    class avem.core.AVButton {
    }
  }
  

  namespace avem.core {
    class avem.core.AVDate {
    }
  }
  

  namespace avem.core {
    class avem.core.AVEquipment {
    }
  }
  

  namespace avem.core {
    class avem.core.AVEquipmentManager {
    }
  }
  

  namespace avem.core {
    class avem.core.AVEvent {
    }
  }
  

  namespace avem.core {
    class avem.core.AVEventManager {
    }
  }
  

  namespace avem.core {
    class avem.core.AVReservation {
    }
  }
  

  namespace avem.core {
    class avem.core.AVReservationManager {
    }
  }
  

  namespace avem.core {
    class avem.core.AVTime {
    }
  }
  

  namespace avem.developer {
    class avem.developer.AdminTools {
    }
  }
  

  namespace avem.main {
    class avem.main.App {
    }
  }
  

  avem.controllers.AccountsViewController .up.|> javafx.fxml.Initializable
  avem.controllers.CheckInOutEquipment .up.|> javafx.fxml.Initializable
  avem.controllers.CheckInOutPageController .up.|> javafx.fxml.Initializable
  avem.controllers.CheckInOutPageController o-- avem.core.AVEquipmentManager : equipmentManager
  avem.controllers.CheckInOutPageController o-- avem.core.AVReservationManager : reservationManager
  avem.controllers.CheckInOutPageController o-- avem.core.AVReservation : selectedReservation
  avem.controllers.DashboardController .up.|> javafx.fxml.Initializable
  avem.controllers.DashboardController o-- avem.core.AVEquipmentManager : equipmentManager
  avem.controllers.DashboardController o-- avem.core.AVReservationManager : reservationManager
  avem.controllers.DashboardController o-- avem.core.AVReservation : selectedReservation
  avem.controllers.Main -up-|> javafx.application.Application
  avem.controllers.MultiSelectTableView -up-|> javafx.scene.control.TableView
  avem.controllers.ReserveEquipment .up.|> javafx.fxml.Initializable
  avem.controllers.ReserveViewController .up.|> javafx.fxml.Initializable
  avem.controllers.ReserveViewController o-- avem.core.AVEquipmentManager : equipmentManager
  avem.controllers.ReserveViewController o-- avem.core.AVEvent : event
  avem.controllers.ReserveViewController o-- avem.core.AVReservation : reservation
  avem.controllers.ReserveViewController o-- avem.core.AVReservationManager : reservationManager
  avem.controllers.SigningController .up.|> javafx.fxml.Initializable
  avem.controllers.SigningController o-- avem.basic.AVEMInfo : accountInfo
  avem.controllers.TableViewController .up.|> javafx.fxml.Initializable
  avem.core.AVButton -up-|> javafx.scene.control.Button
  avem.core.AVButton o-- avem.core.AVReservation : reservation
  avem.core.AVEvent o-- avem.core.AVDate : eventDate
  avem.core.AVEvent o-- avem.core.AVTime : eventEndTime
  avem.core.AVEvent o-- avem.core.AVTime : eventStartTime
  avem.core.AVReservation o-- avem.core.AVEvent : event


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
