@startuml
'https://plantuml.com/object-diagram

object AVEvent {
    - avID = "232"
    - eventName = "Board of Directors Meeting"
    - eventVenue = "Conference Room A"
    - eventDepartment = "President's Office"
    - eventStatus = "Ongoing"
    - contactPerson = "Ms. Katherine Cheng"
    - contactNumber = "104"
    - approvedBy = "Executive Office"
    - encodedBy = "Raul"
    - additionalNotes = "None."
}

object AVDate {
    - day = "15"
    - month = "12"
    - year = "2021"
}

object AVTimeStart {
    - hours = "8"
    - minutes = "00"
    - timeOfDay = "AM"
}

object AVTimeEnd {
    - hours = "8"
    - minutes = "00"
    - timeOfDay = "AM"
}

object AVReservation {
    - equipmentStatus = "CHECKED_OUT"
}



object AVEquipment01 {
    - brand = "Lenovo"
    - currentLocation = "Storage"
    - equipmentID = "305"
    - imgFilePath = "NA"
    - isAvailable = true
    - name = "Lenovo IDEAPAD"
    - notes = "NA"
    - serialNumber = "LN9827155"
    - type = "Laptop"
}

object AVEquipment02 {
    - brand = "Nikon"
    - currentLocation = "Storage"
    - equipmentID = "356"
    - imgFilePath = "NONE"
    - isAvailable = true
    - name = "Nikon N2"
    - notes = "None"
    - serialNumber = "NK23922455"
    - type = "Camera"
}

object AVEquipment03 {
    - brand = "EPSON"
    - currentLocation = "Storage"
    - equipmentID = "422"
    - imgFilePath = "NONE"
    - isAvailable = true
    - name = "EPSON Small"
    - notes = "Bring bag."
    - serialNumber = "EPS381757"
    - type = "Projector"
}

AVEvent --up> AVReservation
AVTimeStart --up-> AVEvent
AVTimeEnd --up-> AVEvent
AVDate -up-> AVEvent

AVEquipment01 ---up> AVReservation
AVEquipment02 ---up> AVReservation
AVEquipment03 ---up> AVReservation
@enduml
